app:
  version: "0.1"

server:
  port: "8181"

spring:
  main:
    banner-mode: "off"

logging:
  level:
    org:
      hibernate: error
      springframework: WARN
    com:
      jp: INFO
      # jp: WARN
    root: WARN
  pattern:
    file: "%d{dd-MM HH:mm} - %-5level - %logger{1} - %msg%n"
  file:
    name: logs/app.log
  config: ./config/logback.xml
